In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print('{0} dimesions, shape: {1}x{2}, element count:{3}, element type: {4}'.format(x.ndim, x.shape[0], x.shape[1], x.size, x.dtype))

2 dimesions, shape: 3x3, element count:9, element type: int32


In [6]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y = np.zeros((4, 5))
z = np.ones((3,8))

In [8]:
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
print(y.reshape((2,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
u = np.empty((3, 5))
print(u)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
r1 = np.arange(1, 10)
r2 = np.arange(1, 10, 2)
r3 = np.arange(1, 10, 0.2)
print(r1)
print(r2)
print(r3)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [22]:
r4 = np.linspace(0, 10, 21)
print(r4)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [25]:
print(a*b)
print(a+b)
print(a-b)
print(a@b)

[[ 5 12]
 [21 32]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]


In [26]:
a

array([[1, 2],
       [3, 4]])

In [27]:
a.ravel()

array([1, 2, 3, 4])

In [28]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
y.shape

(4, 5)

In [31]:
y.reshape(2,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
x.T.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
yy = np.random.random((4, 5))

In [38]:
yy

array([[0.03095528, 0.03321445, 0.76125324, 0.96259834, 0.72062007],
       [0.41434626, 0.95872471, 0.41617381, 0.36409881, 0.81492192],
       [0.03312342, 0.03208525, 0.58354964, 0.22031024, 0.60070801],
       [0.47906817, 0.00802025, 0.32902644, 0.4558947 , 0.43401274]])

In [39]:
yy.T

array([[0.03095528, 0.41434626, 0.03312342, 0.47906817],
       [0.03321445, 0.95872471, 0.03208525, 0.00802025],
       [0.76125324, 0.41617381, 0.58354964, 0.32902644],
       [0.96259834, 0.36409881, 0.22031024, 0.4558947 ],
       [0.72062007, 0.81492192, 0.60070801, 0.43401274]])

In [44]:
np.random.randint(10, size=(4, 5))

array([[9, 4, 2, 6, 6],
       [7, 0, 6, 4, 5],
       [4, 9, 8, 4, 5],
       [6, 4, 6, 9, 3]])

In [45]:
a

array([[1, 2],
       [3, 4]])

In [46]:
b

array([[5, 6],
       [7, 8]])

In [48]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
s = np.hstack((a,b))

In [51]:
s

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
s[:, 0:3]

array([[1, 2, 5],
       [3, 4, 7]])

In [56]:
s[:1,:2]

array([[1, 2]])

In [57]:
s[0]

array([1, 2, 5, 6])

In [58]:
s[0][:1]

array([1])

In [59]:
s[0][:2]

array([1, 2])

In [60]:
a

array([[1, 2],
       [3, 4]])

In [61]:
t = np.array([1, 2, 3])

In [62]:
t

array([1, 2, 3])

In [63]:
t.shape

(3,)

In [64]:
t[:]

array([1, 2, 3])

In [65]:
t[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [69]:
type(np.newaxis)

NoneType

In [70]:
print(np.newaxis)

None


In [71]:
t[:, None]

array([[1],
       [2],
       [3]])

In [72]:
t[:, None, None]

array([[[1]],

       [[2]],

       [[3]]])

In [74]:
p = np.array([1, 2, 3])

In [75]:
p

array([1, 2, 3])

In [76]:
p.shape

(3,)

In [77]:
p[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [78]:
p[np.newaxis, :]

array([[1, 2, 3]])

In [79]:
p[:, np.newaxis].shape

(3, 1)

In [80]:
p[np.newaxis, :].shape

(1, 3)

In [81]:
p.shape

(3,)

In [82]:
p

array([1, 2, 3])

In [83]:
p.shape

(3,)

In [84]:
p1 = np.array([[1, 2, 3]])

In [85]:
p1

array([[1, 2, 3]])

In [86]:
p1.shape

(1, 3)

In [87]:
p2 = np.array([[1], [2], [3]])

In [88]:
p2

array([[1],
       [2],
       [3]])

In [89]:
p2.shape

(3, 1)

In [90]:
p[np.newaxis, :]

array([[1, 2, 3]])

In [91]:
p[np.newaxis, :].shape

(1, 3)

In [92]:
p[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [93]:
p[:, np.newaxis].shape

(3, 1)

In [94]:
p[:, np.newaxis, np.newaxis].shape

(3, 1, 1)